# Generated by Django 4.1.2 on 2023-05-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName_author', models.CharField(help_text='Введите имя автора(Обязательно)', max_length=255, null=True, verbose_name='Имя автора')),
                ('lastName_author', models.CharField(help_text='Введите фамилию автора(Обязательно)', max_length=255, null=True, verbose_name='Фамилия автора')),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_book', models.CharField(help_text='Введите жанр произведения', max_length=255, verbose_name='Жанр произведения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(help_text='Введите название произведения(Обязательно)', max_length=255, unique=True, verbose_name='Название')),
                ('censor', models.CharField(choices=[('C', 'Для детей'), ('G', 'Для взрослых'), ('A', 'Для всех')], default=('G', 'Для взрослых'), help_text='Введите тип произведеня', max_length=255, verbose_name='Цензура')),
                ('content_book', models.TextField(help_text='Введите текст произведения(Обязательно)', verbose_name='Текст')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookauthor')),
                ('genre_book', models.ManyToManyField(to='books.bookgenre')),
            ],
        ),
    ]
